# Generated by Django 5.1.1 on 2024-12-18 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("user_pw", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SearchedMidpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
                ("place_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searched_midpoints",
                        to="meetapp.user",
                    ),
                ),
            ],
        ),
    ]
